### PR TITLE
ARM: dts: qcom: Fix xbl_region reserved memory

### PR DESCRIPTION
**Pull request by Aquarius223**
Typos, it will report memory misalignment and memory leak warnings in dmesg

### CODE REVIEW

**Comment by jjpprrrr** [comment]
What is the dmesg error exactly?

**Comment by stic-server-open** [comment]
> dmesg错误到底是什么？

swapper的memoryleak

**Comment by jjpprrrr** [comment]
What is the error message? I have never seen it.

**Comment by jjpprrrr** [comment]
Merged.

**Pull request closed without merging**
